name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup ESLint
        run: npm install eslint-plugin-import@^2.22.0 \
          eslint-plugin-jsx-a11y@^6.3.1 \
          eslint-plugin-react@^7.20.3 \
          eslint-plugin-react-hooks@^4.0.8 \
          @typescript-eslint/eslint-plugin@^4.4.1 \
          --save-dev
      - name: ESLint Report
        run: npx eslint .
